version: "3.7"
services:

  expect-at-io:
    container_name: expect-at-io
    image: ulvestuen/expect-at-io:latest
    ports:
      - "5000:5000"
    command: "0.0.0.0"

  mock-wiremock:
    container_name: mock-wiremock
    image: mock-wiremock:latest
    depends_on:
      - expect-at-io